version: '3'

services:
  elasticsearch:
    image: elasticsearch:5.6.4-alpine
    ports:
      - 9200:9200
  logstash:
    image: logstash:5.6.4-alpine
    volumes:
      - ./:/gonsan:ro
    entrypoint:
      - /gonsan/entrypoint.sh
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:5.6.4
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
